### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by remychantenay** [bojand/grpcannon#17]
It would be a good thing to be able to set headers.

**Comment by bojand** [comment]
Hello, do you mean the metadata? It can be done using `-m` and `-M` flags as documented:
```
-m  Request metadata as stringified JSON.
-M  Path for call metadata JSON file. For example, /home/user/metadata.json or ./metadata.json.
```
Is this not working for your scenario?

**Comment by remychantenay** [comment]
Indeed, I completely missed this one.

My apologies... 🤦‍♂️ 

Thank you for providing _grpcannon_. Amazing tool 👍
